### ISSUE TITLE
cobbblestone in the early game ?

### ISSUE THREAD

**Issue by Stormwolve** [sebinside/CraftBlock#67]
is it normal that you can get only cobblestone by the unique crop seed that takes long to grow and automate you need lava because you cant right click harvest the cobble seed and other option is destroying the island for cobblestone  because the pebbles from garden of glass dont have a crafting recipe

**Comment by joblo2213** [comment]
Yes it is intentional that cobble has to be mined from the island in the beginning
You need an orechid from botania to create some coal, grind it to dust using Astral Sorcery and then create some Amplifying Tubes to melt cobble into lava.
Then you can create a Cobble/Stone Generator to manually mine cobble, or use the Cobblonia Seeds that periodically drops cobble when grown between Lava and Water.

**Comment by Stormwolve** [comment]
Okay thnaks for the help
