### ISSUE TITLE
Unique Crops feeling grindy and "weird"

### ISSUE THREAD

**Issue by DisguisedDumbass** [sebinside/CraftBlock#88]
First of all i am sorry for the giant wall of text.

I feel like I have some issues regarding the Unique Crops stuff in this modpack.
This might be just individual or unexperienced player things, but i want to explain my concerns anyway.

So here is an TL;DR:

### TL;DR:
- Getting and crafting Unique Crops seeds feels a bit to grindy and repetitive
- Feroxia plant feeling buggy due to unclear behaviour and guidance (adressed)
- The mod itself beeing not documented very well, especially in-game (Only thing I found was the github wiki)
- Some items beeing unoptainable, but still visible in JEI

### 1. Grind and Repetition(Addressed, some crops drop seeds when broken by hand)
- The start of Unique Crops feels nice, because it is a mod that is not that popular so it feels refreshing.
    But reaching the tiers of crops that don't drop their seeds anymore when harvested starts to feel grindy.
   (Scientia, Ender Lily, Dirigible Plum, Weeping Bell. not dropping their seeds anymore)

- This feels grindy, because you for example need 64x Dirigle Plums (dropping randomly) for 16x Ender Lily seeds.
   This 16x Ender Lily seeds beeing needed for 4x Weeping Bells. You cant accelerate some of these growth-rates so you
   just need to wait for them to grow. You also need to craft these seeds several times and not grow or use them in other ways.
  _You essentialy craft seeds to reach a new tier, only to craft 16 more of these seeds for the next tier._

- You also need the Feroxia to give 16x essence (needing it to grow 16x times) to craft enough nether warts for both the warts 
   itself and soul sand (Nether warts beeing essetial gate for Botania fire runes )

### 2. Feroxia (Addressed)
- The Feroxia feels buggy, because i am unable to progress from step 4:
![feroxia](https://user-images.githubusercontent.com/40601725/136286710-6dd61df6-ee0e-4bcc-837d-59ee489dda7a.PNG)

- The in-game guide also beeing unclear on what is needed for the next growth stages in some cases.

- Which leads to the next issue:

### 3. Mod Documentation
- I am aware of the wiki (https://github.com/bafomdad/uniquecrops/wiki), but the overall information is still thin especialy in- 
  game. So sometimes you're stuck because you don't know how certain crops work or are supposed to work. You also can't 
  really see what crops drop when harvested.

### 4. Items an Tweaking
- Some items are unoptainable e.g. the Dark Block requiring the Petramia, which needs bedrock to work.
  This beeing the only recipe based issue I encountered so far, but I don't really know the mod, so there might be more of these.

**Comment by joblo2213** [comment]
Let me address some of this stuff as I spend quite some time with playing the modpack:

1. I can say in fact that is not the case. I have tons of ender lily seeds from my ender lily farm that I automated using botania and it only consists of a single growing plant and is **not** running 24/7 on a server.  
Maybe you need to break the crop (not just right-click-harvest) to obtain seeds.  
From there it is actually not that hard to get enough stuff for feroxia seeds.

I agree that it is overall extreemly annoying and way to grindy. Especially growing Wheeping Balls and Feroxia are just pure hate.

2. I DON'T KNOW WHY THIS FUCKING PLANT DOESN'T WANT TO GROW!!! 😡 
  Been there... 100 times.....

3. I don't think the problem is the level of documentation. A part of playing is just try and error till it works. Not everything should be served to the player, he does need to do a little bit of thinking and testing as well.  
The problem is that so many of this just takes ages so try and error gets really annoying.

4. It's quite good that they are unobtainable as the baubles crafted from the dark block are completely op.  
  In my opinion these items should just be disabled.

**Comment by sebinside** [comment]
Some TODOS to at least partially fix this issue:
- [ ] Add note on how to obtain `Invisibilia Twines`
- [ ] Add recipe to get 4 snowballs out of on snow block
- [ ] Add note on how to obtain `normie seeds`
- [ ] Add note that `feroxia` seeds might need some backup first :)
- [ ] At least temporary disable all baubles
